// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package schema

import (
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type Session struct {
	ID               int32
	UserID           int32
	TokenHash        string
	RefreshTokenHash sql.NullString
	ExpiresAt        time.Time
	UserAgent        sql.NullString
	IpAddress        pqtype.Inet
	CreatedAt        time.Time
	UpdatedAt        time.Time
	DeletedAt        sql.NullTime
}

type User struct {
	ID           int32
	Name         string
	Email        string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    sql.NullTime
}
