// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: queries.sql

package schema

import (
	"context"
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

const createSession = `-- name: CreateSession :execresult

INSERT INTO sessions (
  user_id,
  token_hash,
  refresh_token_hash,
  expires_at,
  user_agent,
  ip_address
) VALUES (
  $1, $2, $3, $4, $5, $6
)
`

type CreateSessionParams struct {
	UserID           int32
	TokenHash        string
	RefreshTokenHash sql.NullString
	ExpiresAt        time.Time
	UserAgent        sql.NullString
	IpAddress        pqtype.Inet
}

// =========================================
// SESSIONS
// =========================================
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.RefreshTokenHash,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.IpAddress,
	)
}

const createUser = `-- name: CreateUser :execresult

INSERT INTO users (
  name, email, password_hash
) VALUES (
  $1, $2, $3
)
`

type CreateUserParams struct {
	Name         string
	Email        string
	PasswordHash string
}

// =========================================
// USERS
// =========================================
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser, arg.Name, arg.Email, arg.PasswordHash)
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions
WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	return err
}

const getSessionByRefreshTokenHash = `-- name: GetSessionByRefreshTokenHash :one
SELECT id, user_id, token_hash, refresh_token_hash, expires_at, user_agent, ip_address, created_at, updated_at, deleted_at FROM sessions
WHERE refresh_token_hash = $1
  AND deleted_at IS NULL
  AND expires_at > NOW()
`

func (q *Queries) GetSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash sql.NullString) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByRefreshTokenHash, refreshTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.RefreshTokenHash,
		&i.ExpiresAt,
		&i.UserAgent,
		&i.IpAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, user_id, token_hash, refresh_token_hash, expires_at, user_agent, ip_address, created_at, updated_at, deleted_at FROM sessions
WHERE token_hash = $1
  AND deleted_at IS NULL
  AND expires_at > NOW()
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.RefreshTokenHash,
		&i.ExpiresAt,
		&i.UserAgent,
		&i.IpAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, name, email, password_hash, created_at, updated_at, deleted_at FROM users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUser(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password_hash, created_at, updated_at, deleted_at FROM users
WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const hardDeleteUser = `-- name: HardDeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) HardDeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, hardDeleteUser, id)
	return err
}

const showSoftDeletedUsers = `-- name: ShowSoftDeletedUsers :many
SELECT id, name, email, password_hash, created_at, updated_at, deleted_at FROM users
WHERE deleted_at IS NOT NULL
`

func (q *Queries) ShowSoftDeletedUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, showSoftDeletedUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteSessionByTokenHash = `-- name: SoftDeleteSessionByTokenHash :exec
UPDATE sessions
SET deleted_at = NOW()
WHERE token_hash = $1
`

func (q *Queries) SoftDeleteSessionByTokenHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, softDeleteSessionByTokenHash, tokenHash)
	return err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, softDeleteUser, id)
	return err
}

const updateSessionRefreshTokenHash = `-- name: UpdateSessionRefreshTokenHash :exec
UPDATE sessions
SET refresh_token_hash = $2
WHERE refresh_token_hash = $1
  AND deleted_at IS NULL
  AND expires_at > NOW()
`

type UpdateSessionRefreshTokenHashParams struct {
	RefreshTokenHash   sql.NullString
	RefreshTokenHash_2 sql.NullString
}

func (q *Queries) UpdateSessionRefreshTokenHash(ctx context.Context, arg UpdateSessionRefreshTokenHashParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionRefreshTokenHash, arg.RefreshTokenHash, arg.RefreshTokenHash_2)
	return err
}

const updateSessionTokenHash = `-- name: UpdateSessionTokenHash :exec
UPDATE sessions
SET token_hash = $2
WHERE token_hash = $1
  AND deleted_at IS NULL
  AND expires_at > NOW()
`

type UpdateSessionTokenHashParams struct {
	TokenHash   string
	TokenHash_2 string
}

func (q *Queries) UpdateSessionTokenHash(ctx context.Context, arg UpdateSessionTokenHashParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionTokenHash, arg.TokenHash, arg.TokenHash_2)
	return err
}
